---
# Centos uses systemd-bus-proxy:ssh_keys for (999:999) which we need to map to
# the tomcat user/group. These are then mapped to the galaxy user over the
# network.
#
# systemd-bus-proxy does not own any files so we're safe there, just remap the
# ID and we should be good to go. Also don't seem to be running any processes
# so that's nice.
#
# [root@apollo /]# find bin boot dev etc home lib lib64 media mnt opt root run srv sys tmp usr var -type f -user systemd-bus-proxy
# [root@apollo /]# find bin boot dev etc home lib lib64 media mnt opt root run srv sys tmp usr var -type f -group systemd-bus-proxy
# [root@apollo /]#
#
#TODO: does not seem to be working?
- name: Check for input group
  command: grep -Fxq "input:x:999" /etc/group
  ignore_errors: yes
  register: check_input
  changed_when: no

# Unfortunately ssh_keys owns some files.
- lineinfile:
    path: /etc/group
    regexp: 'input:x:999:'
    line: 'input:x:500:'
  when: check_input.rc == 0

- command: "find / -gid 999 -exec chgrp 500 '{}' +"
  ignore_errors: yes
  when: check_input.rc == 0

- name: Check for polkitd
  command: grep -Fxq "polkitd:x:999" /etc/passwd
  ignore_errors: yes
  register: check_polkitd
  changed_when: no

- lineinfile:
    path: /etc/passwd
    regexp: 'polkitd:x:999:998:User for polkitd:/:/sbin/nologin'
    line: 'polkitd:x:500:998:User for polkitd:/:/sbin/nologin'
  when: check_polkitd.rc == 0

- command: "find / -uid 999 -exec chown 500 '{}' +"
  ignore_errors: yes
  when: check_polkitd.rc == 0
