---
- name: Include CentOS8 tasks
  include: centos8.yml
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '8'

- name: Include CentOS7 tasks
  include: centos7.yml
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'
